# Generated by Django 2.2.7 on 2019-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('pfx', 'beg', 'end'), name='plan_unique_constraint'),
        ),
    ]
