# Generated by Django 2.2.7 on 2019-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_plan', '0002_auto_20191119_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='capacity',
            field=models.IntegerField(db_index=True),
        ),
    ]
